const Music = [
    {
        title: 'Liked Songs',
        subdesc: '',
        img: 'liked-songs-300.png',
        ispinned: true,
        whatis: 'Playlist',
    },
    {
        title: 'noxuro',
        subdesc: 'noxuro',
        img: 'apfs.jpg',
        ispinned: true,
        whatis: 'Artist',
    },
    {
        title: 'Liked Songs2',
        subdesc: 'nigger6',
        img: 'apfs.jpg',
        ispinned: true,
        whatis: 'Artist',
    },
    {
        title: 'Liked Songs3',
        subdesc: 'nigger3',
        img: 'apfs.jpg',
        ispinned: true,
        whatis: 'Playlist',
    },
    {
        title: 'Liked Songs4',
        subdesc: 'nigger4',
        img: 'apfs.jpg',
        ispinned: true,
        whatis: 'Playlist',
    },
    {
        title: 'Liked Songs3',
        subdesc: 'nigger3',
        img: 'apfs.jpg',
        ispinned: true,
        whatis: 'Playlist',
    },
    {
        title: 'Liked Songs3',
        subdesc: 'nigger3',
        img: 'apfs.jpg',
        ispinned: true,
        whatis: 'Playlist',
    },
    {
        title: 'Liked Songs3',
        subdesc: 'nigger3',
        img: 'apfs.jpg',
        ispinned: true,
        whatis: 'Playlist',
    },
    {
        title: 'Liked Songs3',
        subdesc: 'nigger3',
        img: 'apfs.jpg',
        ispinned: true,
        whatis: 'Playlist',
    },
    {
        title: 'Liked Songs3',
        subdesc: 'nigger3',
        img: 'apfs.jpg',
        ispinned: true,
        whatis: 'Playlist',
    },
    {
        title: 'Liked Songs3',
        subdesc: 'nigger3',
        img: 'apfs.jpg',
        ispinned: true,
        whatis: 'Playlist',
    },
    {
        title: 'Liked Songs3',
        subdesc: 'nigger3',
        img: 'apfs.jpg',
        ispinned: true,
        whatis: 'Playlist',
    },
    {
        title: 'Liked Songs3',
        subdesc: 'nigger3',
        img: 'apfs.jpg',
        ispinned: true,
        whatis: 'Playlist',
    },
    {
        title: 'Liked Songs3',
        subdesc: 'nigger3',
        img: 'apfs.jpg',
        ispinned: true,
        whatis: 'Playlist',
    },
    {
        title: 'Liked Songs3',
        subdesc: 'nigger3',
        img: 'apfs.jpg',
        ispinned: true,
        whatis: 'Playlist',
    },
    {
        title: 'Liked Songs3',
        subdesc: 'nigger3',
        img: 'apfs.jpg',
        ispinned: true,
        whatis: 'Playlist',
    },
    
]

export default Music;